{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 73,
   "id": "50f2b3bd",
   "metadata": {},
   "outputs": [],
   "source": [
    "import telegram\n",
    "import requests\n",
    "from telegram.ext import Updater\n",
    "from telegram.ext import MessageHandler, Filters\n",
    "from bs4 import BeautifulSoup \n",
    "from selenium import webdriver\n",
    "import urllib.request as req\n",
    "import os\n",
    "from selenium.webdriver.support.ui import WebDriverWait\n",
    "from selenium.webdriver.support import expected_conditions as EC\n",
    "from selenium.webdriver.common.by import By"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 74,
   "id": "923523e3",
   "metadata": {},
   "outputs": [],
   "source": [
    "options = webdriver.ChromeOptions()\n",
    "options.add_argument('headless')\n",
    "options.add_argument('window-size=1920x1080')\n",
    "options.add_argument(\"disable-gpu\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 75,
   "id": "b6fce032",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    }
   ],
   "source": [
    "def covid_num_crawling():\n",
    "    code = req.urlopen(\"https://search.naver.com/search.naver?where=nexearch&sm=top_hty&fbm=0&ie=utf8&query=%ED%99%95%EC%A7%84%EC%9E%90\")\n",
    "    soup = BeautifulSoup(code, \"html.parser\")\n",
    "    info_num = soup.select(\"div.status_info em\")\n",
    "    result = info_num[0].string \n",
    "    return result\n",
    "\n",
    "def covid_news_crawling():\n",
    "    code = req.urlopen(\"https://search.naver.com/search.naver?where=news&sm=tab_jum&query=%EC%BD%94%EB%A1%9C%EB%82%98\")\n",
    "    soup = BeautifulSoup(code, \"html.parser\")\n",
    "    title_list = soup.select(\"a.news_tit\")\n",
    "    output_result = \"\"\n",
    "    for i in title_list:\n",
    "        title = i.text\n",
    "        news_url = i.attrs[\"href\"]\n",
    "        output_result += title + \"\\n\" + news_url + \"\\n\\n\"\n",
    "        if title_list.index(i) == 2:\n",
    "            break\n",
    "    return output_result\n",
    "\n",
    "def n_weather_crawling():\n",
    "    code = req.urlopen(\"https://search.naver.com/search.naver?where=nexearch&sm=top_sly.hst&fbm=0&acr=1&ie=utf8&query=%EB%82%A0%EC%94%A8\")\n",
    "    soup = BeautifulSoup(code, \"html.parser\")\n",
    "    weather_info = soup.select(\"div.status_wrap span\")\n",
    "    result = weather_info[0].string \n",
    "    return result\n",
    "    \n",
    "def weather_news_crawling():\n",
    "    code = req.urlopen(\"https://search.naver.com/search.naver?where=video&sm=tab_jum&query=%EB%82%A0%EC%94%A8\")\n",
    "    soup = BeautifulSoup(code, \"html.parser\")\n",
    "    title_list = soup.select(\"a.info_title\")\n",
    "    output_result = \"\"\n",
    "    for i in title_list:\n",
    "        title = i.text\n",
    "        news_url = i.attrs[\"href\"]\n",
    "        output_result += title + \"\\n\" + news_url + \"\\n\\n\"\n",
    "        if title_list.index(i) == 2:\n",
    "            break\n",
    "    return output_result\n",
    "\n",
    "def movie_chart_crawling():\n",
    "    session=requests.Session()\n",
    "    addr='http://movie.naver.com/movie/running/current.nhn'\n",
    "    req=session.get(addr)\n",
    "    soup=BeautifulSoup(req.text,'html.parser')\n",
    "    titles=soup.find_all('dl',class_='lst_dsc')\n",
    "    cnt=1 \n",
    "    output=\" \"\n",
    "    for title in titles:\n",
    "        output+=str(cnt)+'위: '+title.find('a').text+'\\n'+addr+title.find('a')['href']+'\\n'\n",
    "        bot.send_message(chat_id=id,text=output)\n",
    "        output=\"\" \n",
    "        cnt+=1\n",
    "        if cnt==6:\n",
    "            break\n",
    "\n",
    "\n",
    "\n",
    "def job_chart_crawling():\n",
    "    addr = 'https://www.jobkorea.co.kr/Top100/?Main_Career_Type=1&Search_Type=2&BizJobtype_Bctgr_Code=0&BizJobtype_Bctgr_Name=%EC%A0%84%EC%B2%B4&BizJobtype_Code=0&BizJobtype_Name=%EC%A0%84%EC%B2%B4&Major_Big_Code=5&Major_Big_Name=%EA%B3%B5%ED%95%99&Major_Code=93&Major_Name=%EC%82%B0%EC%97%85%EA%B3%B5%ED%95%99%EA%B3%BC&Edu_Level_Code=9&Edu_Level_Name=%EC%A0%84%EC%B2%B4&Edu_Level_Name=%EC%A0%84%EC%B2%B4&MidScroll=0&duty-depth1=on'\n",
    "    driver.get(addr)\n",
    "    job = driver.page_source\n",
    "    soup = BeautifulSoup(job, 'html.parser')\n",
    "    title = soup.select(' div div.coTit  b')\n",
    " \n",
    "    titles = []\n",
    "    for i,j in enumerate(title):\n",
    "        if i < 10:\n",
    "            tts = str(i) + ' ' + j.get_text()\n",
    "            titles.append(tts)\n",
    "\n",
    "    output=\" \"\n",
    "\n",
    "    for i in range(0,10):\n",
    "\n",
    "        output+=str(i+1)+': '+str(titles[i][2:])+'\\n'\n",
    "            \n",
    "    return output\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 76,
   "id": "d6b735ba",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<telegram.message.Message at 0x24895822440>"
      ]
     },
     "execution_count": 76,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "token = \"2049595900:AAHZuIf0uydrz9rlt4Xx25G-AV6dy0gopq0\"\n",
    "id = \"2020049784\"\n",
    "bot = telegram.Bot(token)\n",
    "info_message = '''*오늘 코로나 확진자 수 : \"코로나\" 입력\n",
    "* 코로나 뉴스 : \"코뉴스\" 입력\n",
    "* 오늘의 날씨 : \"날씨\" 입력 \n",
    "* 기상 캐스터: \"기상청\" 입력\n",
    "* 영화 랭킹 : \"영화\" 입력\n",
    "* 산업공학 취업 공고: \"취업\" 입력'''\n",
    "bot.sendMessage(chat_id=id, text=info_message)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 77,
   "id": "9efd4647",
   "metadata": {},
   "outputs": [],
   "source": [
    "updater = Updater(token=token, use_context=True)\n",
    "dispatcher = updater.dispatcher\n",
    "updater.start_polling()\n",
    "\n",
    "def handler(update, context):\n",
    "    user_text = update.message.text \n",
    "    if (user_text == \"코로나\"):\n",
    "        covid_num = covid_num_crawling()\n",
    "        bot.send_message(chat_id=id, text=\"오늘 확진자 수 : {} 명\".format(covid_num))\n",
    "        bot.sendMessage(chat_id=id, text=info_message)\n",
    "    elif (user_text == \"코뉴스\"):\n",
    "        covid_news = covid_news_crawling()\n",
    "        bot.send_message(chat_id=id, text=covid_news)\n",
    "        bot.sendMessage(chat_id=id, text=info_message)\n",
    "    elif(user_text==\"날씨\"):\n",
    "        n_weather=n_weather_crawling()\n",
    "        bot.send_message(chat_id=id,text=\"오늘 날씨의 {}\".format(n_weather))\n",
    "        bot.sendMessage(chat_id=id,text=info_message)  \n",
    "        \n",
    "    elif(user_text==\"기상청\"):\n",
    "        weather_news= weather_news_crawling()\n",
    "        bot.send_message(chat_id=id, text=weather_news)\n",
    "        bot.sendMessage(chat_id=id, text=info_message)\n",
    "        \n",
    "    elif(user_text==\"영화\"):\n",
    "        bot.send_message(chat_id=id, text=\"1위~5위 랭킹\")\n",
    "        movie_chart=movie_chart_crawling()\n",
    "        bot.send_message(chat_id=id,text=movie_chart)\n",
    "        bot.sendMessage(chat_id=id,text=info_message)     \n",
    "\n",
    "        \n",
    "    elif( user_text==\"취업\"):\n",
    "        job_chart=job_chart_crawling()\n",
    "        bot.send_message(chat_id=id, text=job_chart)\n",
    "        bot.sendMessage(chat_id=id, text=info_message) "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 78,
   "id": "6d7340b5",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\dispatcher.py\", line 555, in process_update\n",
      "    handler.handle_update(update, self, check, context)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\handler.py\", line 198, in handle_update\n",
      "    return self.callback(update, context)\n",
      "  File \"<ipython-input-67-7b355bf316a5>\", line 33, in handler\n",
      "    job_chart=job_chart_crawling()\n",
      "  File \"<ipython-input-75-b040125b39e9>\", line 61, in job_chart_crawling\n",
      "    driver.get(addr)\n",
      "NameError: name 'driver' is not defined\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\winni\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    }
   ],
   "source": [
    "echo_handler = MessageHandler(Filters.text, handler)\n",
    "dispatcher.add_handler(echo_handler)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1683ede6",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6457a07f",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5b6fedee",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2e218275",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
